- name: Ubuntu System Update
  apt:
    update_cache: yes
  changed_when: false
  register: update_cache_output

- name: Upgrade All Packages
  apt:
    upgrade: dist
  register: upgrade_cache_output

- name: Clean Up Package Cache
  apt:
    autoclean: yes

- name: Ubuntu Initial Packages Installation 
  apt:
    name: "{{ packages }}"
    state: latest
  register: install_packages_output

- name: Display Debug Output
  debug:
    var: item
  loop:
    - "{{ update_cache_output }}"
    - "{{ upgrade_cache_output }}"
    - "{{ install_packages_output }}"